import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    ListFlowable,
    ListItem
)


# =====================================================
# Generate PDF Report
# =====================================================

def generate_pdf(result):

    # ---------------------------------------------
    # Create reports folder
    # ---------------------------------------------

    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    REPORT_FOLDER = os.path.join(BASE_DIR, "static", "reports")

    os.makedirs(REPORT_FOLDER, exist_ok=True)

    # ---------------------------------------------
    # File name
    # ---------------------------------------------

    filename = f"MindSense_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    filepath = os.path.join(REPORT_FOLDER, filename)

    # ---------------------------------------------
    # PDF Document
    # ---------------------------------------------

    doc = SimpleDocTemplate(filepath)

    styles = getSampleStyleSheet()

    story = []

    # ---------------------------------------------
    # Title
    # ---------------------------------------------

    title = Paragraph(
        "<b><font size=22 color='blue'>MindSense AI</font></b>",
        styles["Title"]
    )

    story.append(title)

    story.append(Spacer(1, 20))

    # ---------------------------------------------
    # Subtitle
    # ---------------------------------------------

    subtitle = Paragraph(
        "<b>Mental Health Assessment Report</b>",
        styles["Heading2"]
    )

    story.append(subtitle)

    story.append(Spacer(1, 20))

    # ---------------------------------------------
    # Date
    # ---------------------------------------------

    story.append(

        Paragraph(

            f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y %I:%M %p')}",

            styles["Normal"]

        )

    )

    story.append(Spacer(1, 15))

    # ---------------------------------------------
    # Prediction
    # ---------------------------------------------

    prediction = result["prediction"]

    color = "green"

    if prediction == "High Risk":
        color = "red"

    story.append(

        Paragraph(

            f"<b>Prediction:</b> <font color='{color}'>{prediction}</font>",

            styles["Heading2"]

        )

    )

    story.append(Spacer(1, 10))

    story.append(

        Paragraph(

            f"<b>Confidence:</b> {result['confidence']}%",

            styles["Normal"]

        )

    )

    story.append(Spacer(1, 25))

    # ---------------------------------------------
    # SHAP Features
    # ---------------------------------------------

    story.append(

        Paragraph(

            "<b>Top Influencing Factors</b>",

            styles["Heading2"]

        )

    )

    story.append(Spacer(1, 10))

    feature_items = []

    for item in result["top_features"]:

        feature_items.append(

            ListItem(

                Paragraph(

                    f"{item['Feature']} : {item['SHAP Value']:.3f}",

                    styles["Normal"]

                )

            )

        )

    story.append(

        ListFlowable(

            feature_items,

            bulletType="bullet"

        )

    )

    story.append(Spacer(1, 25))

    # ---------------------------------------------
    # Recommendations
    # ---------------------------------------------

    story.append(

        Paragraph(

            "<b>Personalized Recommendations</b>",

            styles["Heading2"]

        )

    )

    story.append(Spacer(1, 10))

    recommendation_items = []

    for rec in result["recommendations"]:

        recommendation_items.append(

            ListItem(

                Paragraph(

                    rec,

                    styles["Normal"]

                )

            )

        )

    story.append(

        ListFlowable(

            recommendation_items,

            bulletType="bullet"

        )

    )

    story.append(Spacer(1, 30))

    # ---------------------------------------------
    # Disclaimer
    # ---------------------------------------------

    story.append(

        Paragraph(

            "<font size=9 color='gray'>"
            "This report is generated by MindSense AI "
            "for educational and research purposes only. "
            "It is not a medical diagnosis. "
            "Please consult a qualified healthcare professional "
            "for clinical advice."
            "</font>",

            styles["Normal"]

        )

    )

    # ---------------------------------------------
    # Build PDF
    # ---------------------------------------------

    doc.build(story)

    return filename